name: Continuous Integration

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changed:
    name: Changed
    uses: ./.github/workflows/changes.yml

  test-parse:
    name: Data Files
    runs-on: self-hosted
    needs: changed
    if: ${{ needs.changed.outputs.workflows == 'true' || needs.changed.outputs.data_files == 'true' }}
    steps:
    - uses: ziproot/endless-sky-test-parse@main

